game.Players:Chat("h/\n\n\n\n\n\n                                                                                                    ")
game.Players:Chat("h/\n\n\n\n\n\n\n                          %&#                                                 .                     ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n                          (/     %/                                        ./#@&.   %.                 ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n                         (,        *&,              /.*%.               *&*         @                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n                        #,          ,/&#(%       .(%#.   #*          /%             @                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n                       ,%            .&@*           **    .%.     (%.               @                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n                       (                  ./                /(  #(                  @                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n                       #                                     ,&(                    @                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       #                                                           .&                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       #                                                           (.                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       #            ,##(                   .****.                 .#                   ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       (,         /#.   *,             .%(       ,&.             .&                    ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       .@.       #,   #@@@@,               /@@&%,  *%            &.                    ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                         %...   %,   .@@@@@,              (@@@@@&.   %        .&*                      ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        . ..   /,    .@@@@@,              (@@@@@@%   */     .,#&&%%%*                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                    ,@.   ,&/  /.     &@@@@               /@@@@@@%    ,          ./&                   ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                      *%       .       ,&&##(.              %@@@#            *&/                       ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        .&/.   ,.                                ,(/        .&/                        ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                         ,%   .(#(,                             , .##/.       .@,                      ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        ,#                            .                       .,(                      ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       .@,..,**.           .../% .#%%%/               ,(%(                             ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                .#%*.                           ,*(%/.                                 ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n%%%(,.,,..                    .&,                                      ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n*%.                            .((                                    ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n*#*                             (*                                  ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n/%,                             ,%.                                ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.%.                                .#                                ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.%,     /                             &,                              ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                              #                              ")
game.Players:Chat("h/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                       ")
