-- Very Epic Moment!
-- Instant Shutdown By Skyz#0003!
-- Thank You For Using This!
-- Inject To Shut The Server Down.

function notify(msg)     game.StarterGui:SetCore("SendNotification", {
Title = "Shutting Down Server...";         
Text = msg;         
Duration = 1;     
}) 
end
notify("Please Wait While We Shut It Down.")
game.Players.LocalPlayer.Chatted:connect(function(msg)
time = string.sub(msg, 9)
 if msg == ":pads" then
local pads = game:GetService("Workspace").Terrain["_Game"].Admin.Pads:GetChildren("Head")
 
game.Players:Chat(":pads")
game.Players:Chat(":pads")
game.Players:Chat(":pads")
game.Players:Chat(":pads")
game.Players:Chat(":pads")
game.Players:Chat(":pads")
game.Players:Chat(":pads")
game.Players:Chat(":pads")

for i, pad in pairs(pads) do
pad.PrimaryPart = pad:FindFirstChild("Head")
local pos = pad.PrimaryPart.CFrame
wait(0)
pad.PrimaryPart.CanCollide = false
pad:SetPrimaryPartCFrame(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
wait(0)
pad:SetPrimaryPartCFrame(pos)
pad.PrimaryPart.CanCollide = true
end
end
 
end)

-- Modifiable Section!
game:GetService'Players':Chat(("m/Server Shutdown Due To The Lack Of Coolness."))
game:GetService'Players':Chat(("m/Server Shutdown Due To The Lack Of Coolness."))
game:GetService'Players':Chat(("m/Server Shutdown Due To The Lack Of Coolness."))
game:GetService'Players':Chat(("char all 774445402"))
game:GetService'Players':Chat(("flash")) 
game:GetService'Players':Chat(("fogend NaN"))
game:GetService'Players':Chat(("music 6591385583"))
game:GetService'Players':Chat(("h/Join For Script."))
game:GetService'Players':Chat(("h/Join For Script."))
wait(0.01)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Quick Message!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Are You Mad That We Crashed Your Server?","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Sorry about that!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Cry about it!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Join Us To Become An Epic Gamer!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("disjcord.gg/fnbz3UNnBx","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Enter This Link In Your Browser To Join Us!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Thank You For Joining Anyways, Enjoy the scripts!","All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Okay Bye!  You Should Leave Now Because I Crashed Your Server","All")
wait(0.2)
-- DONT EDIT THIS AREA!! THIS IS HOW THE SHUTDOWN FUNCTIONS...
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("size all 0.3"))
game:GetService'Players':Chat(("freeze all"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("size all 10"))
game:GetService'Players':Chat(("clone all"))
wait(1)
function notify(msg)     game.StarterGui:SetCore("SendNotification", {
Title = "Server Shutted Down!";         
Text = msg;         
Duration = 1;     
}) 
end
notify("1 Process Terminated")
wait(0.5)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
wait(2.50)
local HttpService, TPService = game:GetService("HttpService"), game:GetService("TeleportService")
local ServersToTP = HttpService:JSONDecode(game:HttpGet("https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100"))
for _, s in pairs(ServersToTP.data) do
   if s.playing ~= s.maxPlayers then
       TPService:TeleportToPlaceInstance(game.PlaceId, s.id)
   end
end
